### ISSUE TITLE
Subtract elementheight from modal

### ISSUE THREAD

**Issue by janstieler** [chinchang/cta.js#11]
Hello,
how can I subtract an elementheight from the modal?

Kind regards.

**Comment by chinchang** [comment]
Please explain a bit more. Not able to understand your question.

**Comment by janstieler** [comment]
Hi,
if I have an headerbar like the Bootstrap navbar and a cta-modal is open it will be invisible.
Also you don't have the possibility to see a menu.
It will be great if I can subtract the height of the navbar from the modalposition.

Hopeful this explain is more understandable :).

**Comment by TiagoGoddard** [comment]
I think he meant he wants the Bootstrap navbar to keep showing when the cta-modal is opened.

**Comment by janstieler** [comment]
Hi,
of course this is the result what I want. But I don't want to realize this with setting the navbar only on position fixed or an higher z-index. I need a calculation solution.

**Comment by chinchang** [comment]
@janstieler Your requirement is very independent of *cta.js*. The library itself just transitions one element to other. Its upto you to style the source and destination elements. In your case, you need to make your modal so that it starts not from very top, but after some spacing to let the header show up (probably using `top: header_height_here`). Again note that, the modal in the demo, is not part of *cta.js*. It there for explaining possibilities with the library.

Closing this issue.
