### ISSUE TITLE
Angular...

### ISSUE THREAD

**Issue by vko-online** [chinchang/cta.js#8]
This looks cool...
I would like to popup modal when user navigates to another page, is that possible? Let's say in page-1 i have a tile (just like in your demo) and when user clicks on it, it goes to page-2 (which has same color and some other stuff, just like in demo) when url changes, from `localhost:3000/#/page-1` to `localhost:3000/#/page-2`. Will this work? Didn't tested, hope i can be useful for web applications

**Comment by chinchang** [comment]
This will require support from Angular router itself because the page will actually change when URL changes and `cta.js` won't be able to work on its own across 2 different DOMs.

There has been recent development towards this in Angular's animation module. Have a look here (ng-animate-ref: https://docs.angularjs.org/api/ngAnimate 

Closing this for now.

**Comment by vko-online** [comment]
Wait, when using ui-router, DOM is not drastically changed, only included `<div ui-view></div>` will be populated, so indeed it's possible, i made a sample, and it worked, with tons of hacks, and animation was sometimes broken, but i think it's really possible.

Any ideas boys?

**Comment by bonbonpiment** [comment]
you mean like this : 
https://libraries.io/bower/angular-hero-ramjet/0.0.4
I find this experiment very impressive !
